-- Crear tipo compuesto DIRECCION_C

CREATE TYPE direccion_c AS (
    region TEXT,
    comuna TEXT,
    calle TEXT,
    numero INT
);

CREATE TABLE CLIENTE(
    RUT_CLIENTE INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    CORREO VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    DIRECCION_CLIENTE DIRECCION_C NOT NULL,
    TELEFONO INTEGER NOT NULL
);
CREATE TABLE PASAJE(
    COD_PASAJE SERIAL PRIMARY KEY,
    RUT_CLIENTE INTEGER NOT NULL,
    COD_VUELO INTEGER NOT NULL,
    N_ASIENTO INTEGER NOT NULL,
    FECHA_V DATE NOT NULL,
    TIPO_PAGO INTEGER NOT NULL,
    TOTAL NUMERIC NOT NULL,
    CONSTRAINT FK_PASAJE_CLIENTE FOREIGN KEY (RUT_CLIENTE) REFERENCES CLIENTE(RUT_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE DETALLE_PASAJE(
    COD_VUELO INTEGER NOT NULL,
    COD_PASAJE INTEGER NOT NULL,
    TOTAL NUMERIC NOT NULL,
    PRIMARY KEY (COD_VUELO, COD_PASAJE),
    FOREIGN KEY (COD_PASAJE) REFERENCES PASAJE(COD_PASAJE) ON DELETE CASCADE
);

CREATE TABLE VUELO(
    COD_VUELO SERIAL PRIMARY KEY,
    ID_AGENCIA INTEGER NOT NULL,
    COD_ITINERARIO INTEGER NOT NULL,
    CANTIDAD_ASIENTO INTEGER NOT NULL,
    VALOR NUMERIC NOT NULL,
    TOTAL_ASIENTOS INTEGER NOT NULL
);

CREATE TABLE AGENCIA(
    ID_AGENCIA SERIAL PRIMARY KEY,
    RUT_AGENCIA INTEGER NOT NULL,
    NOMBRE_AGENCIA VARCHAR(100) NOT NULL,
    DIRECCION_A DIRECCION_C NOT NULL,
    TELEFONO INTEGER
);

CREATE TABLE ITINERARIO(
    COD_ITINERARIO SERIAL PRIMARY KEY,
    FECHA_VUELO DATE NOT NULL,
    HORA_SALIDA TIMESTAMP NOT NULL,
    HORA_LLEGADA TIMESTAMP NOT NULL,
    COD_ORIGEN INTEGER NOT NULL,
    COD_DESTINO INTEGER NOT NULL
);

CREATE TABLE ORIGEN(
    COD_ORIGEN SERIAL PRIMARY KEY,
    AEROPUERTO VARCHAR(100) NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
    PAIS VARCHAR(100) NOT NULL
);

CREATE TABLE DESTINO(
    COD_DESTINO SERIAL PRIMARY KEY,
    AEROPUERTO_D VARCHAR(100) NOT NULL,
    CIUDAD_D VARCHAR(100) NOT NULL,
    PAIS_D VARCHAR(100) NOT NULL
);

CREATE TABLE ENCUESTA(
    RUT_CLIENTE INTEGER NOT NULL,
    COD_PASAJE INTEGER NOT NULL,
    ATENCION INTEGER,
    CALIDAD INTEGER,
    RAPIDEZ INTEGER,
    PRIMARY KEY (RUT_CLIENTE, COD_PASAJE),
    FOREIGN KEY (RUT_CLIENTE) REFERENCES CLIENTE(RUT_CLIENTE) ON DELETE CASCADE,
    FOREIGN KEY (COD_PASAJE) REFERENCES PASAJE(COD_PASAJE) ON DELETE CASCADE
);

CREATE TABLE CARRITO(
    RUT_CLIENTE INTEGER NOT NULL,
    COD_VUELO INTEGER NOT NULL,
    TOTAL NUMERIC NOT NULL,
    PRIMARY KEY (RUT_CLIENTE, COD_VUELO),
    FOREIGN KEY (RUT_CLIENTE) REFERENCES CLIENTE(RUT_CLIENTE) ON DELETE CASCADE,
    FOREIGN KEY (COD_VUELO) REFERENCES VUELO(COD_VUELO) ON DELETE CASCADE
);

CREATE TABLE BANCO(
    TARJETA BIGINT PRIMARY KEY,
    CVV INTEGER NOT NULL
);

-- RELACIONES
ALTER TABLE VUELO ADD CONSTRAINT FK_VUELO_AGENCIA FOREIGN KEY(ID_AGENCIA) REFERENCES AGENCIA(ID_AGENCIA) ON DELETE CASCADE;
ALTER TABLE VUELO ADD CONSTRAINT FK_VUELO_ITINE FOREIGN KEY(COD_ITINERARIO) REFERENCES ITINERARIO(COD_ITINERARIO) ON DELETE CASCADE;
ALTER TABLE ITINERARIO ADD CONSTRAINT FK_ITI_ORIGEN FOREIGN KEY(COD_ORIGEN) REFERENCES ORIGEN(COD_ORIGEN) ON DELETE CASCADE;
ALTER TABLE ITINERARIO ADD CONSTRAINT FK_ITI_DESTINO FOREIGN KEY(COD_DESTINO) REFERENCES DESTINO(COD_DESTINO) ON DELETE CASCADE;


INSERT INTO ORIGEN VALUES(1,'ARAUCANIA','TEMUCO','CHILE');
INSERT INTO ORIGEN VALUES(2,'PANGUILEMO','TALCA','CHILE');
INSERT INTO ORIGEN VALUES(3,'CHACALLUTA','ARICA','CHILE');--WEB
INSERT INTO ORIGEN VALUES(4,'INDEPENDENCIA','RANCAGUA','CHILE');--WEB
INSERT INTO ORIGEN VALUES(5,'MATAVERY','ISLA DE PASCUA','CHILE');--WEB
INSERT INTO ORIGEN VALUES(6,'ARTURO BENITEZ','SANTIAGO','CHILE');
INSERT INTO ORIGEN VALUES(7,'CARRIEL SUR','CONCEPCION','CHILE');
INSERT INTO ORIGEN VALUES(8,'CA�AL BAJO CARLOS HOTT SIEBERT','OSORNO','CHILE');

INSERT INTO DESTINO VALUES(1,'EUROPCAR','PUERTO MONTT','CHILE');--WEB
INSERT INTO DESTINO VALUES(2,'TONGOY','COQUIMBO','CHILE');--WEB
INSERT INTO DESTINO VALUES(3,'ARTURO BENITEZ','SANTIAGO','CHILE');
INSERT INTO DESTINO VALUES(4,'PICHOY','VALDIVIA','CHILE');--WEB
INSERT INTO DESTINO VALUES(5,'CHACALLUTA','ARICA','CHILE');--WEB
INSERT INTO DESTINO VALUES(6,'DIEGO ARACENA','IQUIQUE','CHILE');--WEB
INSERT INTO DESTINO VALUES(7,'LA FLORIDA','LA SERENA','CHILE');
INSERT INTO DESTINO VALUES(8,'DESIERTO DE ATACAMA','ATACAMA','CHILE');
INSERT INTO DESTINO VALUES(9,'JORGE CHAVEZ','LIMA','PERU');
INSERT INTO DESTINO VALUES(10,'MILAN-MALPENSA','MILAN','ITALIA');
INSERT INTO DESTINO VALUES(11,'BORYSPIL','KIEW','RUSIA');
INSERT INTO DESTINO VALUES(12,'PARIS-CHARLES DE GAULLE','PARIS','FRANCIA');
INSERT INTO DESTINO VALUES(13,'MIAMI INTERNTIONAL AIRPORT','MIAMI','EEUU');
INSERT INTO DESTINO VALUES(14,'JOSEP TARRADELLAS BARCELONA-EL PRAT','BARCELONA','ESPA�A');



INSERT INTO ITINERARIO VALUES(1,'2020-02-06', '2020-02-06 18:30:00', '2020-02-06 21:30:00',1,1);--temuco a pto
INSERT INTO ITINERARIO VALUES(2,'2025-03-06', '2025-03-06 18:30:00', '2025-03-06 21:30:00',2,2);
INSERT INTO ITINERARIO VALUES(3,'2025-03-06', '2025-03-06 18:30:00', '2025-03-06 21:30:00',3,3);
INSERT INTO ITINERARIO VALUES(4,'2025-03-16', '2025-03-16 8:30:00', '2025-03-16 21:30:00',4,4);--ran--valdivia

INSERT INTO ITINERARIO VALUES(5,'2025-03-07', '2025-03-07 18:30:00', '2025-03-07 21:30:00',5,5);
INSERT INTO ITINERARIO VALUES(6,'2025-03-07', '2025-03-07 18:30:00', '2025-03-07 21:30:00',6,6);--santi --iqui


INSERT INTO AGENCIA VALUES(102,56300200,'LATAM',ROW('METROPOLITANA','SANTIAGO','GRAL BULNES ',83),269555689);
INSERT INTO AGENCIA VALUES(103,765748798,'JETSMART',ROW('METROPOLITANA','SANTIAGO','HUECHURABA ',61),600600131);
INSERT INTO AGENCIA VALUES(104,765748798,'SKY AIRLINE',ROW('METROPOLITANA','SANTIAGO','AV DEL VALLE ',573),600600298);
INSERT INTO AGENCIA VALUES(105,743747388,'AER LINGUS',ROW('MADRID','MADRID','CALLE PRINCESA ',2),474737344);

INSERT INTO VUELO VALUES(1000,102,1,50,2000,20);
INSERT INTO VUELO VALUES(1001,102,2,2,3000,20);
INSERT INTO VUELO VALUES(1002,102,4,20,6000,20);



INSERT INTO CLIENTE (RUT_CLIENTE, NOMBRE, APELLIDO, CORREO, FECHA_NACIMIENTO, DIRECCION_CLIENTE, TELEFONO) VALUES
(201437067, 'SERGIO', 'LEON', 'S2@A', '1999-02-24', ROW('OHIGGINS', 'MARCHIGUE', 'ARTUTO PRAT', 54)::DIRECCION_C, 992527915),
(101232964, 'JOSE', 'PERALTA', 'DE2@A', '2000-07-14', ROW('MAULE', 'VILLA ALEGRE', '4 NORTE', 58)::DIRECCION_C, 78222242);



INSERT INTO PASAJE VALUES(1000,201437067,1000,2,TO_DATE('30-12-2021','DD-MM-YYYY'),1,0);--orden de envio
INSERT INTO PASAJE VALUES(1004,201437067,1000,1,TO_DATE('30-12-2021','DD-MM-YYYY'),1,0);


INSERT INTO PASAJE VALUES(1005,201437067,1002,2,TO_DATE('31-12-2020','DD-MM-YYYY'),1,0);
INSERT INTO PASAJE VALUES(1007,201437067,1002,1,TO_DATE('31-12-2020','DD-MM-YYYY'),1,0);

