-- Vista que selecciona todos los datos de ORIGEN
CREATE OR REPLACE VIEW VISTA_DATO AS 
SELECT * FROM ORIGEN;

-- Vista que selecciona todos los datos de DESTINO
CREATE OR REPLACE VIEW VISTA_DATO2 AS 
SELECT * FROM DESTINO;

-- Vista de CLIENTES, extrayendo los campos de DIRECCION_CLIENTE
CREATE OR REPLACE VIEW VISTA_CLIENTES AS 
SELECT 
    c.RUT_CLIENTE, 
    c.NOMBRE, 
    c.APELLIDO, 
    c.CORREO, 
    c.FECHA_NACIMIENTO,
    (c.DIRECCION_CLIENTE).region AS REGION, 
    (c.DIRECCION_CLIENTE).comuna AS COMUNA, 
    (c.DIRECCION_CLIENTE).calle AS CALLE, 
    (c.DIRECCION_CLIENTE).numero AS NUMERO, 
    c.TELEFONO 
FROM CLIENTE c;


-- Vista de VUELOS
CREATE OR REPLACE VIEW VISTA_VUELOS AS 
SELECT * FROM VUELO;

-- Vista de AGENCIAS, suponiendo que AGENCIA también tiene un tipo compuesto de dirección
CREATE OR REPLACE VIEW VISTA_AGENCIAS AS 
SELECT a.ID_AGENCIA, 
       a.RUT_AGENCIA, 
       a.NOMBRE_AGENCIA, 
       (a.DIRECCION_A).region AS region,
       (a.DIRECCION_A).comuna AS comuna, 
       (a.DIRECCION_A).calle AS calle, 
       (a.DIRECCION_A).numero AS numero
FROM AGENCIA a;

-- Vista de ITINERARIOS
CREATE OR REPLACE VIEW VISTA_ITINERARIOS AS 
SELECT * FROM ITINERARIO;

-- Vista con datos básicos de agencias, extrayendo la región de DIRECCION_A
CREATE OR REPLACE VIEW datos_agencia AS 
SELECT a.NOMBRE_AGENCIA, 
       (a.DIRECCION_A).region AS region, 
       a.TELEFONO 
FROM AGENCIA a;

-- Vista de ENCUESTAS
CREATE OR REPLACE VIEW VISTA_ENCUESTAS AS 
SELECT * FROM ENCUESTA;

-- Vista de VUELOS con datos combinados
CREATE OR REPLACE VIEW VUELOS AS 
SELECT o.CIUDAD, 
       d.CIUDAD_D, 
       i.FECHA_VUELO, 
       v.VALOR
FROM ORIGEN o
JOIN ITINERARIO i ON o.COD_ORIGEN = i.COD_ORIGEN
JOIN DESTINO d ON i.COD_DESTINO = d.COD_DESTINO
JOIN VUELO v ON v.COD_ITINERARIO = i.COD_ITINERARIO;

-- Vista de PASAJES
CREATE OR REPLACE VIEW VISTA_PASAJES AS 
SELECT * FROM PASAJE;

-- Vista con información de cantidad de asientos en un vuelo
CREATE OR REPLACE VIEW VUELO_T AS 
SELECT v.COD_VUELO, 
       v.CANTIDAD_ASIENTO, 
       v.TOTAL_ASIENTOS 
FROM VUELO v;

-- Vista con información extendida de vuelos
CREATE OR REPLACE VIEW vuelos_de AS 
SELECT v.COD_VUELO, 
       o.CIUDAD, 
       d.CIUDAD_D, 
       i.FECHA_VUELO, 
       v.CANTIDAD_ASIENTO 
FROM ORIGEN o
JOIN ITINERARIO i ON o.COD_ORIGEN = i.COD_ORIGEN
JOIN DESTINO d ON i.COD_DESTINO = d.COD_DESTINO
JOIN VUELO v ON v.COD_ITINERARIO = i.COD_ITINERARIO;

-- Vista del DETALLE_CARRITO
CREATE OR REPLACE VIEW DETALLE_CARRITO AS 
SELECT C.RUT_CLIENTE, 
       V.COD_VUELO, 
       V.VALOR 
FROM CARRITO C
JOIN VUELO V ON V.COD_VUELO = C.COD_VUELO;

-- Vista de CARRITO
CREATE OR REPLACE VIEW VISTA_CARRITO AS 
SELECT * FROM CARRITO;
